### ISSUE TITLE
bug in example atom feed

### ISSUE THREAD

**Issue by Alloyed** [Osmose/phantomake#3]
https://osmose.ceo/phantomake/examples/atom_feed.html#feedxmlejs

```
      <entry>
        <!-- Use the frontmatter (available under file.attributes) to fill out post info. -->
        <title><%- file.attributes.title %></title>
        <link href="<%- ctx.absolutify(file.url) %>" />
        <id><%- ctx.tagUri(ctx.absolutify(file.url)) %></id>
        <published><%- ctx.formatDate(file.attributes.date) %></published>
      </entry>
```

surprise! ctx.tagUri() uses the current date if don't provide one, meaning your posts will always change ids every time you update the site, at least one day after original upload.

![image](https://github.com/user-attachments/assets/738bafd5-340f-4a14-8895-d94a49e39760)

my fix:
```
        <id><%- ctx.tagUri(ctx.absolutify(file.url), file.attributes.date) %></id>
```

should the id include a date at all? /shrug

**Comment by Osmose** [comment]
Ahhh, good catch, yeah that example should have a date, will add it when I can. It probably shouldn't even have a default and instead throw an error if you don't provide a date to prevent this.

As for whether it _should_ include the date, the [tag URI](https://en.wikipedia.org/wiki/Tag_URI_scheme) standard says:

> The date is chosen to make the tagging entity globally unique, exploiting the fact that domain names and email addresses are assigned to at most one entity at a time.  That entity then ensures that it mints unique identifiers.

I dunno that it _really_ matters that much for RSS, esp. since you might want to update the date on a post without RSS readers thinking it's a completely different post, but anyone who really cares can just ignore `ctx.tagUri` and make their own IDs.
